virt:
  username: hunantv
  password: hunantv123
  keyname: rsa
  redis: 2.8.11
  nutcracker: 0.3.0
  servers:
    - 10.1.201.49
    - 10.1.201.48

unknown:
  username: hunantv
  password: hunantv123
  keyname: rsa
  redis: 2.8.11
  nutcracker: 0.3.0
  servers:
    - 10.1.201.49

u2:
  username: hunantv
  password: hunantv123
  keyname: rsa
  redis: 2.8.11
  nutcracker: 0.3.0
  servers:
    - 10.1.201.48
